#pragma once
#include <memory>
#include <list>
#include <iostream>
#include <stdlib.h>
#include <stdio.h>
#include <gl/glew.h>
#include <gl/freeglut.h>
#include <gl/freeglut_ext.h>
#include <gl/glm/glm.hpp>
#include <gl/glm/ext.hpp>
#include <gl/glm/gtc/matrix_transform.hpp>
#include <array>
#include <algorithm>
#include <random>
#include <cmath>
#include "GlobalUtility.h"